### ISSUE TITLE
pip install grape failure on support_luca>=1.0.2

### ISSUE THREAD

**Issue by amc-corey-cox** [AnacletoLAB/grape#17]
I am attempting to install grape using pip on Ubuntu 20.04.4 LTS with python 3.8.3.

Most of the build/install appears to work just fine until I hit this error, providing a little additional context. I have also tried to install ensmallen directly with `pip install ensmallen` and I get the same error. Any advice you have would be appreciated.

```
Requirement already satisfied: idna<3,>=2.5 in /home/corey/anaconda3/lib/python3.8/site-packages (from requests->bioregistry>=0.5.65->ensmallen>=0.8.21->grape) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/corey/anaconda3/lib/python3.8/site-packages (from requests->bioregistry>=0.5.65->ensmallen>=0.8.21->grape) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /home/corey/anaconda3/lib/python3.8/site-packages (from requests->bioregistry>=0.5.65->ensmallen>=0.8.21->grape) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/corey/anaconda3/lib/python3.8/site-packages (from requests->bioregistry>=0.5.65->ensmallen>=0.8.21->grape) (3.0.4)
Collecting typing-extensions>=3.7.4.3
  Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
ERROR: Could not find a version that satisfies the requirement support_luca>=1.0.2 (from dict_hash>=1.1.25->cache_decorator>=2.1.11->ensmallen>=0.8.21->grape) (from versions: none)
ERROR: No matching distribution found for support_luca>=1.0.2 (from dict_hash>=1.1.25->cache_decorator>=2.1.11->ensmallen>=0.8.21->grape)
```

**Comment by LucaCappelletti94** [comment]
Oh, sorry, that's a typo from a release from yesterday of a package of mine. I am fixing that, ETA 5 minutes tops.

**Comment by amc-corey-cox** [comment]
I can see you've already fixed it. I have successfully installed grape. I'm so glad I opened an issue instead of pounding my head against this. Thanks!

**Comment by LucaCappelletti94** [comment]
I have now released the version with the updated requirements, namely `grape==0.1.23`.
You can get it by either running `pip install grape -U` or, more specifically, `pip install grape==0.1.23`.
It may take about a minute for PyPi to propagate the package.

Thank you very much for pointing this error out!
I had an error related to protected branches, and I did not notice my fix was gotten rejected by GitHub.

**Comment by LucaCappelletti94** [comment]
@amc-corey-cox one more thing: if you encounter any other issue or you have doubts on how to use something, you can readily find either me or @zommiommy available in the [Telegram group](https://t.me/grape_lib).
