### ISSUE TITLE
Link to "manually compile Ensmallen" is broken

### ISSUE THREAD

**Issue by RemyLau** [AnacletoLAB/grape#21]
In the latest version (0.1.24), the link in the README for "manually compile Ensmallen" (https://github.com/AnacletoLAB/ensmallen/blob/master/bindings/python/README.md) is broken

**Comment by LucaCappelletti94** [comment]
Thank you for reporting this! I will identify where that was moved.

**Comment by LucaCappelletti94** [comment]
Link updated! Again, thank you for reporting this.
