### ISSUE TITLE
embiggen package error under Windoze 

### ISSUE THREAD

**Issue by RichardBruskiewich** [AnacletoLAB/grape#22]
The joy on installation on Windoze...

```
Collecting embiggen>=0.11.9
  Downloading embiggen-0.11.38.tar.gz (154 kB)
     ---------------------------------------- 154.2/154.2 kB ? eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\cygwin64\tmp\pip-install-37lyy1_b\embiggen_3ec9ca91df6044b1b2470bb84cb6184d\setup.py", line 54, in <module>
          long_description=readme(),
        File "C:\cygwin64\tmp\pip-install-37lyy1_b\embiggen_3ec9ca91df6044b1b2470bb84cb6184d\setup.py", line 12, in readme
          return f.read()
        File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 2: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by LucaCappelletti94** [comment]
Hi! Thank you for reporting this issue!
The cause is likely some character in the package description that your system does not support. I will try to identify which one it is.

**Comment by LucaCappelletti94** [comment]
I may have fixed it!

Since I do not have access to any Windows machine, could I possibly ask you to join the Telegram or Discord groups to coordinate a test together?

**Comment by RichardBruskiewich** [comment]
> I may have fixed it!
> 
> Since I do not have access to any Windows machine, could I possibly ask you to join the Telegram or Discord groups to coordinate a test together?

LOL, what's Telegram or Discord? 

I must be too close to retirement and kind of losing track of all these technical communication channels popping up...

**Comment by LucaCappelletti94** [comment]
From version `0.1.25`, this issue should be resolved. Could you please try and let me know?

Thanks!

**Comment by RichardBruskiewich** [comment]
Hi @LucaCappelletti94, I reran the poetry update and install. Things seem to work now. I'll let you know if anything else arises. Thanks!

**Comment by LucaCappelletti94** [comment]
Hi Richard, in our tests also windows works. What error are you still encountering?
