### ISSUE TITLE
PyPI metadata is broken

### ISSUE THREAD

**Issue by cthoyt** [AnacletoLAB/grape#5]
The current release on PyPI points to https://github.com/LucaCappelletti94/grape in the homepage, which apparently wasn't gracefully transferred so it doesn't know to redirect here. If you update that metadata in the setup.py

https://github.com/AnacletoLAB/grape/blob/fabc7ab025dd4b5fca0c3d3bccf90c37262deaee/setup.py#L49

and release again, this should resolve itself

**Comment by LucaCappelletti94** [comment]
This is now fixed, thank you for reporting it!
