### ISSUE TITLE
Error in "compute_node_embedding"

### ISSUE THREAD

**Issue by smsnia** [AnacletoLAB/grape#7]
I ran the default pipeline of using CBOW, SkipGram and Glove to embed Cora.ipynb. The pipeline successfully ran without error until it reached to "compute_node_embedding" where the following error appeared:
IndexError                                Traceback (most recent call last)
[<ipython-input-9-5ffe4b3926cd>](https://localhost:8080/#) in <module>()
      6 first_order_rw_node_embedding, training_history = compute_node_embedding(
      7     graph,
----> 8     node_embedding_method_name=node_embedding_method_name,
      9 )
      ...
      IndexError: pop from empty list

**Comment by LucaCappelletti94** [comment]
Hello @smsnia, this was born out of a bug in new TensorFlow releases and we have now found a working patch for this. We are now integrating this patch in the library and soonish publishing this on Pypi.

**Comment by LucaCappelletti94** [comment]
The patched version is available on Pypi. Do note that the version code with the patch is `0.0.6.dev3`

**Comment by LucaCappelletti94** [comment]
Please do let me know if everything works fine now.
